import Head from 'next/head';
import { useState } from 'react';
// import Image from 'next/image';

export default function Home() {

  const [products, setProducts] = useState([
    {
      "productId": 1,
      "productName": "Monitor LED 27'' Gamer Curvo Samsung 1920 x 1080 FHD 240 Hz HDMI, DP, Gsync Série CRG50",
      "productImage": "/static/images/products/image-1.png",
      "favorite": false,
      "productLink": "#",
      "productAlt": "Monitor LED 27&#34; Gamer Curvo Samsung 1920 x 1080 FHD 240 Hz HDMI, DP, Gsync Série CRG50",
      "productDiscount": "R$ 2.813,99",
      "productPrice": "R$ 2.599,00",
      "productInstallment": "10x de R$ 259,90",
      "cart": false
    },
    {
      "productId": 2,
      "productName": "Monitor LED 27'' Gamer Curvo Samsung 1920 x 1080 FHD 240 Hz HDMI, DP, Gsync Série CRG50",
      "productImage": "static/images/products/image-2.png",
      "favorite": false,
      "productLink": "#",
      "productAlt": "Monitor LED 27&#34; Gamer Curvo Samsung 1920 x 1080 FHD 240 Hz HDMI, DP, Gsync Série CRG50",
      "productDiscount": "R$ 2.813,99",
      "productPrice": "R$ 2.599,00",
      "productInstallment": "10x de R$ 259,90",
      "cart": false
    },
    // {
    //   "productId": 3,
    //   "productName": "Monitor LED 27'' Gamer Curvo Samsung 1920 x 1080 FHD 240 Hz HDMI, DP, Gsync Série CRG50",
    //   "productImage": "static/images/products/image-2.png",
    //   "favorite": false,
    //   "productLink": "#",
    //   "productAlt": "Monitor LED 27&#34; Gamer Curvo Samsung 1920 x 1080 FHD 240 Hz HDMI, DP, Gsync Série CRG50",
    //   "productDiscount": "R$ 2.813,99",
    //   "productPrice": "R$ 2.599,00",
    //   "productInstallment": "10x de R$ 259,90",
    //   "cart": false
    // },
    // {
    //   "productId": 4,
    //   "productName": "Monitor LED 27'' Gamer Curvo Samsung 1920 x 1080 FHD 240 Hz HDMI, DP, Gsync Série CRG50",
    //   "productImage": "static/images/products/image-2.png",
    //   "favorite": false,
    //   "productLink": "#",
    //   "productAlt": "Monitor LED 27&#34; Gamer Curvo Samsung 1920 x 1080 FHD 240 Hz HDMI, DP, Gsync Série CRG50",
    //   "productDiscount": "R$ 2.813,99",
    //   "productPrice": "R$ 2.599,00",
    //   "productInstallment": "10x de R$ 259,90",
    //   "cart": false
    // }
  ]);

  const [productsCart, setProductsCart] = useState([]);
  const [favorites, setFavorites] = useState([]);

  function handleFavorite(e) {
    if (e.favorite) {
      let index = products.findIndex(index => index.productId === e.productId);
      let newArray = [...products];
      newArray[index] = {...newArray[index], favorite: false};
      setProducts(newArray);

      let newFavorites = [...favorites];
      let newFavoriteIndex = newFavorites.findIndex(index => index.productId === e.productId);
      
      if (newFavoriteIndex !== -1) {
        newFavorites.splice(newFavoriteIndex, 1);
        setFavorites(newFavorites);
      }
    }
    else {
      let index = products.findIndex(index => index.productId === e.productId);
      let newArray = [...products];
      newArray[index] = {...newArray[index], favorite: true};
      setProducts(newArray);

      let newValue = {...e, favorite: true};
      setFavorites([...favorites, newValue])
    }
  }

  function handleAddCart(obj) {
    let index = products.findIndex(index => index.productId === obj.productId);
    let newArray = [...products];
    newArray[index] = {...newArray[index], cart: true};
    setProducts(newArray);

    let sendProductCart = {...obj, cart: true}
    setProductsCart([...productsCart, sendProductCart]);
  }
  
  console.log("Items added to cart", productsCart);
  console.log("Favorites", favorites);

  return (
    <>
      <Head>
        <title>B8ONE - Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <div className="products">
          <div className="products__boxes">
            {
              products.map((obj) => {
                return (
                  <div className="products__box" key={obj.productId}>
                    <div className="products__image-box">
                      <img className="products__image" src={obj.productImage} alt={obj.productAlt} />
                      <input type="checkbox" className="products__checkbox" checked={obj.favorite} onChange={() => handleFavorite(obj)} id={`favorite-${obj.productId}`} />
                      <label className="products__box-favorite" htmlFor={`favorite-${obj.productId}`}>
                        <svg className="products__icon" fill="none" xmlns="http://www.w3.org/2000/svg">
                          <path className="products__icon-path-1" d="M23.1494 2.85655C22.5629 2.26797 21.8667 1.80107 21.1003 1.48251C20.334 1.16396 19.5126 1 18.6831 1C17.8535 1 17.0321 1.16396 16.2658 1.48251C15.4994 1.80107 14.8032 2.26797 14.2167 2.85655L12.9997 4.07749L11.7826 2.85655C10.5981 1.66822 8.99152 1.00062 7.31633 1.00062C5.64114 1.00062 4.03455 1.66822 2.85001 2.85655C1.66547 4.04489 1 5.65662 1 7.33718C1 9.01774 1.66547 10.6295 2.85001 11.8178L4.06705 13.0387L12.9997 22L21.9323 13.0387L23.1494 11.8178C23.7361 11.2295 24.2015 10.531 24.519 9.76219C24.8366 8.99339 25 8.16936 25 7.33718C25 6.50499 24.8366 5.68096 24.519 4.91216C24.2015 4.14336 23.7361 3.44486 23.1494 2.85655Z" fill="white" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                        </svg>
                      </label>
                    </div>
                    <h4 className="heading-4">
                      {
                        obj.productName
                      }
                    </h4>
                    <div className="products__prices">
                      <span className="products__discount">
                        {
                          obj.productDiscount
                        }
                      </span>
                      <span className="products__price">
                        {
                          obj.productPrice
                        }
                      </span>
                      <span className="products__installment">
                        em até <span className="products__amount-installments">{obj.productInstallment}</span> sem juros
                      </span>
                    </div>
                    <input type="checkbox" className="products__checkbox" id="button-1" />
                    <div className={obj.cart ? "button button--green-2 u-margin-top-32" : "button button--green u-margin-top-32"} onClick={() => { handleAddCart(obj) }}>
                      {
                        obj.cart ?
                          <>
                            <svg className="button__check" viewBox="0 0 18 13" fill="none" xmlns="http://www.w3.org/2000/svg">
                              <path className="button__check-path-1" d="M17 1L6 12L1 7" stroke="#1C1C1C" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                            </svg>
                            <span className="button__added button__added--black">Adicionado</span>
                          </>
                          : <span className="button__added button__added--white">Adicionar</span>
                      }
                    </div>
                  </div>
                )
              })
            }
          </div>
        </div>
      </div>
    </>
  )
}
